apiVersion: v1
kind: Pod
metadata:
  name: NULL                              # instance Id
  # namespace: kube-test
  labels:
    app: NULL                             # service Name微服务名称
spec:
  containers:
    - name: NULL
      image: NULL
      imagePullPolicy: Always
      ports:
        - containerPort: NULL
      volumeMounts:
        - mountPath: /var/data/traceData
          name: trace_path
      readinessProbe:
        tcpSocket:
          port: NULL
        initialDelaySeconds: 160
        periodSeconds: 10
        timeoutSeconds: 5
#      env: # java的环境变量
#        - name: REGISTRY
#          value: "10.244.2.2:8080"
  volumes:
    - name: trace_path
      hostPath:
        path: /data/liulei/traceInfo
  nodeSelector:
    node: null
